### ISSUE TITLE
Playground application throwing errors on launch from Visual Studio

### ISSUE THREAD

**Issue by thehetz** [Microsoft/PowerBI-visuals#436] opened 2016-06-03 13:34 UTC
I have followed the instructions in the ReadMe and have installed the VS add-on as well.  I have built without errors but when I launch the application in IE I first get this error reported: 
Line:120
Error: Unable to get property 'DataViewTransform' of undefined or null reference

Followed by this one:
Line: 133
Error: '$' is undefined

I have also built using the command line whith no change to the issue.

**Comment by ignatvilesov** [comment] 2016-06-07 07:12
Marking this as a duplicate of #437.

**Closed by ignatvilesov** 2016-06-07 07:12 UTC
