### ISSUE TITLE
How to debug "An error occurred while rendering the report" in the desktop

### ISSUE THREAD

**Issue by TonyGaul** [microsoft/PowerBI-visuals#58] opened 2016-08-23 14:03 UTC
Hi,

I've been struggling for a while with debugging a custom visual which works well but always throws an error when loading in Power BI desktop.  I have many copies of this KPI in a desktop report and I can't figure out why I get this error.  I have 12 copies of this custom visual and I get 12 error messages whenever I open the desktop file which contains the visuals.

"Microsoft.Mashup.Host.Document.JavaScriptException: An error occurred while rendering the report.
   at :line 0

Invocation Stack Trace:

   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.ClientShared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace)
   at Microsoft.Mashup.Client.ClientShared.FeedbackErrorInfo..ctor(String message, Nullable`1 errorCode, String requestId, Exception exception)
   at Microsoft.Mashup.Client.ClientShared.UnexpectedExceptionHandler.<>c__DisplayClass1.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass3.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.ClientShared.WindowManager.ShowDialog[T](T form, IWin32Window owner)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClassc.<Main>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

JS Error Message
Script error."

The visual also works well in PowerBI.com, except the icon doesn't show properly.  I am using the web dev tools to create this as some features aren't supported by the CLI tools.

Any assistance would be appreciated as I have spent a lot of time trying to figure this out myself and am struggling!
[FinancialKPI.1.7.2.pbiviz.zip](https://github.com/Microsoft/PowerBI-visuals/files/432579/FinancialKPI.1.7.2.pbiviz.zip)

Thanks,
Tony

**Comment by spatney** [comment] 2016-08-23 17:49
Sure, we'll look into this.

**Comment by TonyGaul** [comment] 2016-08-23 22:24
Thanks Sachin.

Also when I view a dashboard on an iPhone using this visual, the visual keeps growing in size.  Well the actual boundary of the tile doesn't change, but it seems like the visual is zooming in / growing in size.  I've tested this on the iPad and it does the same thing, BUT it works OK on different Android and Windows mobile devices.  The report containing the visual doesn't zoom, just the dashboard tile.

Where's the best place to raise this issue?  Can I leave it here or raise a different a new request?  I have attached a movie showing the issue...

[Zooming visual.zip](https://github.com/Microsoft/PowerBI-visuals/files/433669/Zooming.visual.zip)

**Comment by v-kazaki** [comment] 2016-08-29 14:55
@TonyGaul, can you share your pbix file? I created report in the latest version of Power BI Desktop using your visual, and couldn't reproduce this issue.

**Comment by TonyGaul** [comment] 2016-08-30 10:42
@v-kazaki Hi Kamil, please find a zip of my issue.  I can reproduce the error, but as mentioned in my documentation I will be working on porting my code over to the new CLI tool soon which may (or may not) fix the issue.

Btw my other scrolling visual issue on the iPhone seems to be fixed with the latest update.  So my second issue can be ignored.

[Sample For Microsoft.zip](https://github.com/Microsoft/PowerBI-visuals/files/444603/Sample.For.Microsoft.zip)

**Comment by v-kazaki** [comment] 2016-09-02 15:03
Thanks, we are looking into this issue.

**Comment by v-kazaki** [comment] 2016-09-12 15:32
@TonyGaul, we addresses your issue. As we see there is no problem in your visual and this issue can be reproduced in Power BI Desktop for other visuals also.

**Comment by TonyG-HD** [comment] 2016-09-12 21:22
Great thanks.  You can close this issue or do what you want with it.  Thanks Tony

**Comment by TonyGaul** [comment] 2016-09-12 21:24
Great thanks. You can close this issue or do what you want with it. Thanks Tony

**Closed** 2020-07-01 15:55 UTC
Labels: Investigation
