### ISSUE TITLE
Unsuccessful using d3.js 4.7.1

### ISSUE THREAD

**Issue by joergplewe** [microsoft/PowerBI-visuals#142] opened 2017-03-06 18:01 UTC
Hi all!

pbiviz demos/tutorials typically rely in d3.js v3.5.5. I tried to update to 4.7.1 but run into issues.

What I did:
* put d3.js 4.7.1 to `package.json`
* referenced d3.js in `externalJS` in `pbiviz.json`
* removed any reference to d3.js from `typings.json` (does not compile otherwise)
* used `@types/d3` in `package.json` instead (compiles and gives full code completion in VSCode)

As this works quite well so far, the issue is that there is no global `d3` object at runtime. I can workaround this by using

```
let w: any = window;
let d3 = w.d3;
```

This gives me access to the 4.7.1 `d3` object, but of course kills code completion in VSCode.

So I have either code completion or a working runtime. Can I have both?

Hope for help, thank you upfront,

. Jörg

**Comment by joergplewe** [comment] 2017-03-20 10:34
I think it might be related to PowerBI sandboxing? Anybody?

**Comment by ignatvilesov** [comment] 2017-03-27 13:12
@joergplewe Yes, you're correct. It's related to Power BI sandbox mode.
We'll have an internal discussion about this problem. I hope that we will find a good solution soon.

We'll let you know as soon as we resolve the issue.

**Comment by domoritz** [comment] 2017-07-07 03:33
This seems to be a duplicate of https://github.com/Microsoft/PowerBI-visuals/issues/98

**Comment by howlowck** [comment] 2018-04-13 14:50
hi you can add to the top of your visual.ts file to get around the compilation error, and `typeof` brings that namespace 

```ts
interface Window {
  d3: typeof d3;
}
```

and to utilize..
```ts
let d3 = window.d3; //d3 now has the right namespace
```

**Closed** 2020-06-29 14:44 UTC
