### ISSUE TITLE
Visual Studio Run: Not loading

### ISSUE THREAD

**Issue by rwedoff** [Microsoft/PowerBI-visuals#438] opened 2016-06-06 18:13 UTC
Following the Readme, I ran the Playground and tried to run it in Visual Studio.  When running, the webpage opens up, but indefinitely loads.
Errors:
01:04:37.0958: Referenced file '../../../lib/powerbi-visuals.all.js' not found.
01:04:37.0958: Referenced file '../../../lib/CustomVisuals.js' not found.
01:04:37.0958: Referenced file 'obj/PowerBIVisualsPlayground.js' not found.

**Comment by ignatvilesov** [comment] 2016-06-07 07:11
Marking this as a duplicate of #437

**Closed by ignatvilesov** 2016-06-07 07:11 UTC
