### ISSUE TITLE
selection id builder for table

### ISSUE THREAD

**Issue by whyvez** [microsoft/PowerBI-visuals#48] opened 2016-08-09 22:50 UTC
I am trying to add a selection manager to my visual. 

Here is my capabilities config: https://github.com/woodbuffalo/powerbi-leaflet/blob/master/capabilities.json

We are using a simple table. In your docs the selection ID builder looks like:

```
let selectionId = host.createSelectionIdBuilder()
            .withCategory(categorical.categories[0], i)
            .withMeasure(dataValue.source.queryName)
            .withSeries(categorical.values, categorical.values[i])
            .createSelectionId();
```

Here is where I am trying to implement the builder: https://github.com/woodbuffalo/powerbi-leaflet/blob/selection/src/visual.ts#L47-L49

Could you post an example of how we would implement our builder?

**Comment by spatney** [comment] 2016-08-09 22:55
the links show a 404. is your repo private?

**Comment by whyvez** [comment] 2016-08-09 23:04
@spatney Oops sorry. Just made public.

**Comment by whyvez** [comment] 2016-08-10 15:31
@spatney  The docs for `ISelectionIdBuilder` and `ISelectionManager` don't seem to be included in the powerbi ts docs (http://microsoft.github.io/PowerBI-visuals/modules/powerbi.html). Is this an older version of the module? If so how would I get to the latest docs?

**Comment by whyvez** [comment] 2016-08-10 16:04
Looks like there is already id's generated for each value in the table if I inspect the dataview within the dev tools. Can I simply use these?
![screen shot 2016-08-10 at 10 03 10 am](https://cloud.githubusercontent.com/assets/1593907/17561122/e031cb9a-5ee1-11e6-9727-4c5b9c5ce968.png)

**Comment by spatney** [comment] 2016-08-10 20:05
We'll add some docs for how to do this for tables soon. Also, https://github.com/woodbuffalo/powerbi-leaflet/blob/selection/src/visual.ts#L4-L5, instead of loading it from the CDN can you just compile it into the visual? This will ensure you don't get strange race conditions.

**Comment by whyvez** [comment] 2016-08-10 20:07
Great thanks. Regarding the CDN yes definitely but how would CSS be loaded?

**Comment by spatney** [comment] 2016-08-10 20:14
I believe you can just add the CSS file to the project, rename the extension to '.less', and import it in visual.less. Alternatively you can import your CSS directly into visual.less. [This stackoverflow thread](http://stackoverflow.com/questions/11196915/import-css-file-into-less-file) has some suggestions.

**Comment by samississipi** [comment] 2016-09-12 03:29
the [sample you offered](https://github.com/woodbuffalo/powerbi-leaflet/blob/selection/src/visual.ts#L47-L49) seems to have several problems:
1. line47: `this` doesn't reference to the visual.
2. line47: selectionIdBuilder is called instead of directly referenced.
3. line48: ISelectionIdBuilder.withSeries doesn't accept `DataViewTableRow[]` as first argument.

it compiles just because the wrong reference accidently skips the syntax check on `withSeries`. problem 3 seems to be an blocking issue to support selection for table view.

is there a more clear sample?

**Comment by Bootta11** [comment] 2016-09-13 09:11
Hello,

I have same problem as samississipi: 

> the sample you offered seems to have several problems:
1. line47: this doesn't reference to the visual.
2. line47: selectionIdBuilder is called instead of directly referenced.
3. line48: ISelectionIdBuilder.withSeries doesn't accept DataViewTableRow[] as first argument.

**Comment by ignatvilesov** [comment] 2017-08-11 07:49
Duplicate of #77

**Comment by helen508light** [comment] 2020-07-01 15:53
duplicate

**Closed by helen508light** 2020-07-01 15:53 UTC
Labels: documentation request
