### ISSUE TITLE
Input text (Objects) does not allow more than 250 characters

### ISSUE THREAD

**Issue by CleberDSantos** [microsoft/PowerBI-visuals#117] opened 2017-01-02 19:22 UTC
I'm trying to create an input text in Objects (capabilities.json) and it has more than 250 characters. I saw that the component has the maxLength = 250. 
 
However, I need to use parameters with text in my visualization.
 
Is it possible to create an textArea in Objects?
<img width="980" alt="9d66fe987c8d4f8a9e065bddba4ab965" src="https://cloud.githubusercontent.com/assets/1626423/21595031/54ee1542-d0f7-11e6-847a-f50a7fbd6b84.png">

**Comment by helen508light** [comment] 2020-07-02 20:39
duplicate of https://github.com/microsoft/PowerBI-visuals/issues/269

Multiline textbox is not supported by PowerBI yet. We'll consider your suggestion in future versions of API.

**Closed by helen508light** 2020-07-02 20:39 UTC
